name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Docs Repo
              uses: actions/checkout@v3
            - name: 'Install NodeJS'
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Docs
              run: npm install

            - name: Build Docs
              run: npm run build:all

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
                  cname: developers.ultra.io
